#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run prettier and eslint on staged files
cd frontend
FILES=$(git diff --cached --name-only --diff-filter=ACM "*.ts" "*.tsx" "*.js" "*.jsx" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format files
echo "$FILES" | xargs npx prettier --write
echo "$FILES" | xargs npx eslint --fix

# Add back the modified files to staging
echo "$FILES" | xargs git add
