table:
  name: applications
  schema: public
insert_permissions:
  - role: public
    permission:
      check: {}
      columns:
        - resume_url
        - created_at
        - company_id
        - id
        - job_id
    comment: ""
  - role: user
    permission:
      check: {}
      columns:
        - resume_url
        - created_at
        - company_id
        - id
        - job_id
    comment: ""
select_permissions:
  - role: public
    permission:
      columns:
        - id
        - resume_url
      filter: {}
    comment: ""
  - role: user
    permission:
      columns:
        - company_id
        - created_at
        - id
        - job_id
        - resume_url
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
    comment: ""
