table:
  name: applications
  schema: public
object_relationships:
  - name: application_stage
    using:
      foreign_key_constraint_on: stage_id
  - name: company
    using:
      foreign_key_constraint_on: company_id
  - name: job
    using:
      foreign_key_constraint_on: job_id
insert_permissions:
  - role: public
    permission:
      check: {}
      columns:
        - resume_url
        - created_at
        - company_id
        - id
        - job_id
    comment: ""
  - role: user
    permission:
      check: {}
      columns:
        - resume_url
        - created_at
        - company_id
        - id
        - job_id
    comment: ""
select_permissions:
  - role: public
    permission:
      columns:
        - company_id
        - created_at
        - id
        - job_id
        - resume_url
        - stage_id
      filter: {}
    comment: ""
  - role: user
    permission:
      columns:
        - company_id
        - created_at
        - email
        - id
        - job_id
        - linkedin
        - match_score
        - name
        - relevant_skills
        - resume_url
        - skills
        - stage
        - stage_id
        - website
        - years_of_experience
      filter:
        company:
          company_users:
            user_id:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
    comment: ""
update_permissions:
  - role: user
    permission:
      columns:
        - stage
        - stage_id
      filter:
        company:
          company_users:
            user_id:
              _eq: X-Hasura-User-Id
      check: null
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        company:
          company_users:
            user_id:
              _eq: X-Hasura-User-Id
    comment: ""
