table:
  name: application_stages
  schema: public
object_relationships:
  - name: job
    using:
      foreign_key_constraint_on: job_id
insert_permissions:
  - role: user
    permission:
      check:
        job:
          company:
            company_users:
              user_id:
                _eq: X-Hasura-User-Id
      columns:
        - description
        - id
        - job_id
        - name
        - user_id
    comment: ""
select_permissions:
  - role: public
    permission:
      columns:
        - created_at
        - description
        - id
        - job_id
        - name
        - updated_at
        - user_id
      filter: {}
    comment: ""
  - role: user
    permission:
      columns:
        - description
        - name
        - created_at
        - updated_at
        - id
        - job_id
        - user_id
      filter: {}
    comment: ""
update_permissions:
  - role: user
    permission:
      columns:
        - description
        - name
      filter:
        job:
          company:
            company_users:
              user_id:
                _eq: X-Hasura-User-Id
      check: null
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        job:
          company:
            company_users:
              user_id:
                _eq: X-Hasura-User-Id
    comment: ""
