-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."applications" add column "years_of_experience" integer
--  null;
